Item.delete_all
User.delete_all
Purchase.delete_all

eren = User.create(first_name: "Eren", last_name: "Yeager", username: "titanhater01", image: "https://avatarfiles.alphacoders.com/823/82387.jpg", email: "stupidtitans@aol.com", bio: "I miss my mom.", password_digest: "1234")
light = User.create(first_name: "Light", last_name: "Yagami", username: "IWin666", image: "https://pm1.narvii.com/6189/c9956bcecd0430f3d76102f99efc43e447cd2e7a_hq.jpg", email: "iamgod@hotmail.com", bio: "I am the greatest man ever. I'm both a hero and a God. Come at me L!", password_digest: "6666")
chika = User.create(first_name: "Chika", last_name: "Fujiwara", username: "ChikaChika", image: "https://www.geekgirlauthority.com/wp-content/uploads/2019/02/kaguyasama-detective-chika-2.png", email: "lovedetective@aol.com", bio: "Leave it to me! I know what I'm doing!", password_digest: "1234")
shinji = User.create(first_name: "Shinji", last_name: "Ikari", username: "goodboy99", image: "https://dotandline.net/wp-content/uploads/2019/06/Shinjiprofil-1024x642.jpg", email: "shinji55", bio: "I don't want to get in the robot!", password_digest: "12345")


product1 = Item.create(name: "1900s Edwardian Gibson Dress ", image: "https://thepragmaticcostumer.files.wordpress.com/2012/03/dressforsale.jpg?w=336&h=240", description: "This is in amazing condition! There are a couple tiny breaks in lace that you really have to search for but no holes or stains! Could be worn with caution. Bodice measures 15” across the shoulders, 40” through the bust, 25” at the waist, and length is 20”. Sleeves are 22” long from shoulder seam to cuff. Length from top of shoulder to waist seam is 17”. Bodice has high neck, lace inserts, floating lace panels around yoke, pigeon breast and full sleeves with fitted lace cuff", category: "fashion", user_id: 1, price: 1323.00, quantity: 1)
product2 = Item.create(name: "1920s Wooden Dresser", image: "https://i.etsystatic.com/9808362/d/il/5d7a87/2686708319/il_340x270.2686708319_csbe.jpg?version=0", description: "This is a beautiful piece in need of love or just to be used as is. The inlay and top piece the top are in such great shape. The original handles are all there - as well as the wooden wheels. They are included with this piece. The top of this piece has a graceful accent attached to the back.", category: "furniture", user_id: 2, price: 423.00, quantity: 1)
product3 = Item.create(name: "10 Rare Coins Set(Some Silver)", image: "https://thumbs.worthpoint.com/zoom/images2/1/0715/22/1944-silver-proof-set-san-francisco_1_c18816feb7d908fb2ee701a0ba02427c.jpg", description: "Silver Coins: One Mercury Dime (90% Silver), Four Franklin Half Dollar (90% Silver), Three Kennedy Half Dollar (40% Silver). Non-Silver Coins: Two Eisenhower (IKE) Dollar", category: "collectibles", user_id: 2, price: 53.95, quantity: 4)
product4 = Item.create(name: "RARE First Edition Great Gatsby", image: "https://robbreport.com/wp-content/uploads/2016/10/grest-gatsby-first-editions-lead.jpg?w=772", description: "This is the first edition, first printing of this story. As such, it is one of the most valuable books in the world of rare & antiquarian books. Bound Cosway-style by Bayntun-Riviere in full red crushed levant morocco leather with five raised bands, spine and covers elaborately tooled and lettered in gilt with the front cover set with a large oval miniature painting of Dickens under glass, gilt dentelles, silk doublures and endpapers, all edges gilt.", category: "miscellaneous", user_id: 1, price: 39522.00, quantity: 1)

